Repository laminas/laminas-session, pull requests merged in 2025-04, with the labels that each got.

#117 Remove MongoDB Support and Prepare Documentation for v3.0
  .github/workflows/continuous-integration.yml
  .laminas-ci.json
  .laminas-ci/install-mongodb-extension-via-pecl.sh
  .laminas-ci/pre-install.sh
  composer.json
  composer.lock
  docs/book/v2/application-integration/usage-in-a-laminas-mvc-application.md
  docs/book/v2/config.md
  docs/book/v2/container.md
  docs/book/v2/installation.md
  docs/book/v2/manager.md
  docs/book/v2/migration/preparing-for-v3.md
  docs/book/v2/save-handler.md
  docs/book/v2/storage.md
  docs/book/v2/validators/csrf.md
  docs/book/v2/validators/httpuseragent.md
  docs/book/v2/validators/introduction.md
  docs/book/v2/validators/remoteaddr.md
  docs/book/v2/validators/writing-custom-validators.md
  docs/book/v3/application-integration/usage-in-a-laminas-mvc-application.md
  docs/book/v3/config.md
  docs/book/v3/container.md
  docs/book/v3/installation.md
  docs/book/v3/manager.md
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/save-handler.md
  docs/book/v3/storage.md
  docs/book/v3/validators/csrf.md
  docs/book/v3/validators/httpuseragent.md
  docs/book/v3/validators/introduction.md
  docs/book/v3/validators/remoteaddr.md
  docs/book/v3/validators/writing-custom-validators.md
  mkdocs.yml
  phpunit.xml.dist
  psalm-baseline.xml
  src/SaveHandler/MongoDB.php
  src/SaveHandler/MongoDBOptions.php
  test/SaveHandler/MongoDBOptionsTest.php
  test/SaveHandler/MongoDBTest.php
Labels: BC Break, Documentation, Feature Removal

#116 Remove Laminas\Db Session Save Handler Support
  .github/workflows/continuous-integration.yml
  .laminas-ci.json
  composer.json
  composer.lock
  docs/book/v2/migration/preparing-for-v3.md
  docs/book/v2/save-handler.md
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/save-handler.md
  phpunit.xml.dist
  psalm-baseline.xml
  src/SaveHandler/DbTableGateway.php
  src/SaveHandler/DbTableGatewayOptions.php
  test/SaveHandler/AbstractDbTableGatewayTestCase.php
  test/SaveHandler/DbTableGateway/MysqliAdapterTest.php
  test/SaveHandler/DbTableGateway/PdoMysqlAdapterTest.php
  test/SaveHandler/DbTableGateway/PdoSqliteAdapterTest.php
  test/SaveHandler/DbTableGateway/PgsqlAdapterTest.php
  test/SaveHandler/DbTableGatewayOptionsTest.php
  test/TestAsset/TestDbTableGatewaySaveHandler.php
Labels: BC Break, Feature Removal

#122 Cache.php deprecations & v3 migration guide update
  docs/book/v2/migration/preparing-for-v3.md
  psalm-baseline.xml
  src/SaveHandler/Cache.php
Labels: Documentation, Enhancement

#129 allow mongodb/mongodb 2.0.0
  composer.json
  composer.lock
Labels: Enhancement, Dependencies

#120 Replace Laminas\Cache requirement with PSR-16 Cache
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Exception/SimpleCacheException.php
  src/Exception/SimpleCacheInvalidArgumentException.php
  src/SaveHandler/Cache.php
  test/SaveHandler/CacheTest.php
  test/SaveHandler/SimpleCacheTest.php
  test/TestAsset/TestSimpleCacheAdapter.php
Labels: BC Break, Documentation Needed, Enhancement
